version: "3"

services:
  frontend:
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    image: brunol1m2/app-frontend:1.0
    restart: always
    ports: 
      - 3000:3000
  backend:
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    image: brunol1m2/api-backend:1.0
    restart: always
    ports:
      - 8080:8080
  
