version: "3"

services:
  backend:
    image: backend:0.0.1-SNAPSHOT
    restart: always
    ports:
      - 8080:8080
db:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Blr2151@
    ports:
      - 5431:5431