version: "3"

services:
  backend:
    image: brunol1m2/api-backend:0.0.1-SNAPSHOT
    restart: always
    ports:
      - 8080:8080
db:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    environment:
      - SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres  
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Blr2151@
    ports:
      - 5432:5432
      